version: "3.9"
services:


  my-doc-backend:
    container_name: my-doc-backend
    build: .
    volumes:
      - .:/app
    ports:
      - "4020:4020"
    env_file:
      - .env

    environment:
      - ENVIRONMENT=prod



# docker directory er terminal e zawar jonne
# docker compose exec <service name> bash

# console er output live dekhar jonne
# docker logs -f <container name>